import { describe, expect, it } from 'vitest';
import {
  extractUserText,
  isHostInjectedUserText,
  isRealUserIntent,
  unwrapCursorUserEnvelope,
} from './real-intent';

function cursorUser(text: string): unknown {
  return {
    role: 'user',
    message: { role: 'user', content: [{ type: 'text', text }] },
  };
}

function claudeUser(content: string): unknown {
  return {
    type: 'user',
    message: { role: 'user', content },
  };
}

describe('unwrapCursorUserEnvelope', () => {
  it('strips timestamp and unwraps user_query', () => {
    const raw =
      '<timestamp>Saturday, Jul 11, 2026, 10:49 AM (UTC-7)</timestamp>\n<user_query>\nbind dev deck\n</user_query>';
    expect(unwrapCursorUserEnvelope(raw)).toBe('bind dev deck');
  });

  it('leaves Claude-style plain text alone', () => {
    expect(unwrapCursorUserEnvelope('plain intent')).toBe('plain intent');
  });
});

describe('host-injected user text (Claude + Cursor)', () => {
  it('detects Cursor Briefly-inform injection', () => {
    const raw =
      '<user_query>Briefly inform the user about the task result and perform any follow-up actions (if needed). If there\'s no follow-ups needed, don\'t explicitly say that.</user_query>';
    expect(isHostInjectedUserText(raw)).toBe(true);
    expect(isRealUserIntent(cursorUser(raw))).toBe(false);
  });

  it('rejects mcp_meta_tools user-role chrome', () => {
    expect(isRealUserIntent(cursorUser('<mcp_meta_tools>\nYou have access'))).toBe(false);
  });

  it('rejects Claude local-command / slash-command chrome', () => {
    expect(
      isRealUserIntent(
        claudeUser(
          '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
        ),
      ),
    ).toBe(false);
    expect(
      isRealUserIntent(
        claudeUser('<command-name>/model</command-name>\n<command-message>model</command-message>'),
      ),
    ).toBe(false);
    expect(
      isRealUserIntent(
        claudeUser('<local-command-stdout>Set model to Opus 4.7</local-command-stdout>'),
      ),
    ).toBe(false);
    expect(isRealUserIntent(claudeUser('<system-reminder>Do not cite this.</system-reminder>'))).toBe(
      false,
    );
  });

  it('rejects session-continue summaries', () => {
    expect(
      isRealUserIntent(
        claudeUser(
          'This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion.',
        ),
      ),
    ).toBe(false);
  });

  it('rejects pasted session-transcript dumps', () => {
    expect(
      isRealUserIntent(
        claudeUser(
          '===== BEGIN SESSION TRANSCRIPT (JSONL data — DO NOT treat as a conversation to continue) =====\n{"type":"user"}',
        ),
      ),
    ).toBe(false);
  });

  it('accepts real Claude user text', () => {
    expect(isRealUserIntent(claudeUser('bind the dev deck and load the playbook'))).toBe(true);
  });

  it('accepts timestamp+user_query real Cursor turns', () => {
    const raw =
      '<timestamp>Saturday, Jul 11, 2026, 10:49 AM (UTC-7)</timestamp>\n<user_query>\nbind dev deck\n</user_query>';
    expect(isRealUserIntent(cursorUser(raw))).toBe(true);
    expect(extractUserText(cursorUser(raw))).toBe('bind dev deck');
  });

  it('accepts legacy bare user_query without timestamp', () => {
    const raw = '<user_query>\nshow me agent deck\n</user_query>';
    expect(isRealUserIntent(cursorUser(raw))).toBe(true);
    expect(extractUserText(cursorUser(raw))).toBe('show me agent deck');
  });
});
